### ISSUE TITLE
mobile web requests go to desktop site

### ISSUE THREAD

**Issue by dtannen** [paypal/adaptivepayments-sdk-php#39]
Using this SDK and it redirect to web version on my mobile device.  I want to use the paypal mobile web checkout (expType=mini).  How do I do that with this SDK?

**Comment by Gaudon** [comment]
I would like to know this as well.

**Comment by ppmtscory** [comment]
Keep in mind that the mini browser (Embedded flow) is not a mobile optimized flow.  It's better for mobile than the web flow because of the minibrowser, but not a true mobile optimized flow.  In the SimpleSamples folder there's the [EmbeddedPay.php](https://github.com/paypal/adaptivepayments-sdk-php/blob/master/samples/SimpleSamples/EmbeddedPay.php) file that shows how to utilize this option.
