### ISSUE TITLE
how to get sandbox credentials 

### ISSUE THREAD

**Issue by astroanu** [paypal/adaptivepayments-sdk-php#55]
I had no place else to ask this but, where to get the sandbox credentials ? 

````
"acct1.UserName" => "jb-us-seller_api1.paypal.com",
				"acct1.Password" => "WX4WTU3S8MY44S7F",
				"acct1.Signature" => "AFcWxV21C7fd0v3bYYYRCpSSRl31A7yDhhsPUU2XhtMoZXsWHFxu-RWy",
				"acct1.AppId" => "APP-80W284485P519543T"
```

The documentation is very badly written in a technical point of view, it says i can get my secret from profile and settings. https://developer.paypal.com/docs/classic/api/apiCredentials/#creating-an-api-signature but i cant seem to find anything similar to what the doc says in my app settings.

**Comment by ppmtscory** [comment]
@astroanu you would login to developer portal and go into your sandbox accounts list.  Once there, click the triangle to expand the line entry for the account you want to use, and click the profile link.  When this opens, there's an API credentials tab that will give you your credentials.  The AppID is the same as in your question above for all of Sandbox so that doesn't change.
